### ISSUE TITLE
Support for AWS_SESSION_TOKEN

### ISSUE THREAD

**Issue by madiganz** [seung-lab/cloud-files#101]
I recently ran into an issue where I could check if a file existed using boto3, but it would fail for CloudFiles. This is because I was required to use `AWS_SESSION_TOKEN` and the current secrets retrieval and boto3 initialization does not support this. I modified some files locally to support this and it seems to work well with minimal code changes. I am happy to create a PR for this. Let me know your thoughts

**Comment by william-silversmith** [comment]
This sounds useful, yes please make a PR ☺️

**Comment by madiganz** [comment]
@william-silversmith created the PR. I did not add any tests for this, but I am happy to add a test that validates that `aws_credentials` contain the `AWS_SESSION_TOKEN` if you would like.

**Comment by william-silversmith** [comment]
Yea, adding that test would be helpful because I'll probably forget about
this. That way if I screw something up it'll alert me.

Thank you!

Will

**Comment by madiganz** [comment]
I added a test for the verification

**Comment by madiganz** [comment]
Please let me know when you create a release with this change.

**Comment by william-silversmith** [comment]
New release uploaded!
