### ISSUE TITLE
numpy import missing

### ISSUE THREAD

**Issue by fcollman** [seung-lab/cloud-files#4]
```
/opt/anaconda3/envs/minnietask/lib/python3.7/site-packages/cloudfiles/lib.py in default(self, obj)
     61 class NumpyEncoder(json.JSONEncoder):
     62   def default(self, obj):
---> 63     if isinstance(obj, np.ndarray):
     64       return obj.tolist()
     65     if isinstance(obj, np.integer):

NameError: name 'np' is not defined
```

**Comment by william-silversmith** [comment]
Do you think a required numpy dependency is okay just to support numpy JSON serialization?

**Comment by fcollman** [comment]
i think numpy is fairly ubiquitous at this point... you could however make it work in a dynamic way.. try except the numpy import and then only support this serialization if it was imported.  Obviously if someone is trying to serialize a numpy result they are going to have it installed in their environment.
