### ISSUE TITLE
dependency of Rust from orjson

### ISSUE THREAD

**Issue by jingpengw** [seung-lab/cloud-files#45]
The orjson requires Rust and I do not have rust in cluster. it is really necessary to use orjson?
is that possible to make it optional? We can use python json in default?

**Comment by jingpengw** [comment]
I have downgraded to 1.14.1 since it do not have this dependency.

**Comment by jingpengw** [comment]
I can use conda install to install orjson without problem.

**Comment by william-silversmith** [comment]
Old versions of Python and old versions of pip might have problems. These
can be solved by upgrading to the latest pip and py3.6+

If you have the problem on a new architecture (e.g. Apple Silicon for
example) please let me know.
