### ISSUE TITLE
`cp -r` semantics

### ISSUE THREAD

**Issue by william-silversmith** [seung-lab/cloud-files#52]
Currently, `cloudfiles cp -r` differs from `cp -r` because unlike with a regular filesystem, object storage doesn't have a convenient `mv` command. So where `cp -r` copies the directory and the subfiles, `cloudfiles cp -r` copies only the subfiles to allow you to specify the level of hierarchy in the destination path.

However, this has caused confusion for several users. Perhaps we could allow `cp -r` to follow POSIX semantics while allowing `cp dir/**` to work like before.

**Comment by nkemnitz** [comment]
Maybe for comparison, gsutil: https://cloud.google.com/storage/docs/gsutil/commands/cp#how-names-are-constructed - I think that's what lab members are probably already familiar with.

[aws s3 cp](https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html) also has a useful `--dryrun` argument
