### ISSUE TITLE
HTTP auth support broken graphene interface

### ISSUE THREAD

**Issue by fcollman** [seung-lab/cloud-files#88]
https://github.com/seung-lab/cloud-files/pull/82/files

This PR assumed that secrets had a particular form, but the Graphene https interface does not share that form, and so code that used to work to access CAVE dynamic datasets is now broken using the latest cloudfiles.

**Comment by william-silversmith** [comment]
I see. This seems like an easy fix.

**Comment by william-silversmith** [comment]
https://github.com/seung-lab/cloud-files/pull/89
