### ISSUE TITLE
Etag validation for S3 Compatible storage / clients

### ISSUE THREAD

**Issue by malagus** [seung-lab/cloud-files#90]
Some of S3 compatible storage / clients use different part size that are hard coded in this lib.  
I my case we use Min IO and sometimes client split files to part that don't follow 1m factor.
For example i get part size 16777728 and last part size is 13911034
Is there any option too disable etag validation or change logic to use head request to get first part size and use it for etag validation?

**Comment by william-silversmith** [comment]
As a hack, you might be able to disable etag checking by specifying a range request (e.g. start=0, end=None). The head trick is a very good tip. I may look into implementing that.
